server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: user1
    password: password1
    url: jdbc:postgresql://postgres:5431/customer
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: false
    register-with-eureka: false
    enabled: false