apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  PGDATA: "/data/postgres"
  PGPORT: "5431"
  POSTGRES_DB: "spring-kubernetes-demo"
  POSTGRES_USER: "user1"
  POSTGRES_PASSWORD: "password1" # Generally should use Secret for that
immutable: true